# Generated by Django 3.2.6 on 2021-09-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_candidate_job_recruiter_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
