# Generated by Django 3.2.6 on 2021-09-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_alter_recruiter_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter', models.CharField(max_length=10)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.job')),
            ],
        ),
    ]
