# Generated by Django 3.2.6 on 2021-09-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
    ]
