# Generated by Django 3.2.6 on 2021-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_remove_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='tool.Skills'),
        ),
    ]
