# Generated by Django 3.2.6 on 2021-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_auto_20210917_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
