# Generated by Django 3.2.6 on 2021-10-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_alter_recruiter_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.job'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.recruiter'),
        ),
    ]
