# Generated by Django 3.2.6 on 2021-10-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0015_auto_20211028_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.job'),
        ),
    ]
