# Generated by Django 3.2.6 on 2021-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_alter_interview_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='interviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
