# Generated by Django 3.2.6 on 2021-10-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_recruiter_interviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.candidate'),
        ),
    ]
