# Generated by Django 3.2.6 on 2021-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_auto_20211029_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter',
            field=models.ManyToManyField(to='tool.Recruiter'),
        ),
    ]
