# Generated by Django 3.2.6 on 2021-10-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0021_auto_20211029_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.recruiter'),
            preserve_default=False,
        ),
    ]
