# Generated by Django 3.2.6 on 2021-10-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0023_alter_candidate_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.recruiter'),
            preserve_default=False,
        ),
    ]
